//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the RESX Manager tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamEcho.App.Resources {
    using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Resources
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		public Resources()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					var temp = new global::System.Resources.ResourceManager("SteamEcho.App.Resources.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		public static string LibraryTitle => ResourceManager.GetString("LibraryTitle", resourceCulture);

		public static string AddGameTooltip => ResourceManager.GetString("AddGameTooltip", resourceCulture);

		public static string SettingsButtonTooltip => ResourceManager.GetString("SettingsButtonTooltip", resourceCulture);

		public static string SearchBarPlaceholder => ResourceManager.GetString("SearchBarPlaceholder", resourceCulture);

		public static string SearchBarTooltip => ResourceManager.GetString("SearchBarTooltip", resourceCulture);

		public static string DeleteOption => ResourceManager.GetString("DeleteOption", resourceCulture);

		public static string BrowseFilesOption => ResourceManager.GetString("BrowseFilesOption", resourceCulture);

		public static string SetExecutableOption => ResourceManager.GetString("SetExecutableOption", resourceCulture);

		public static string WelcomeMessage => ResourceManager.GetString("WelcomeMessage", resourceCulture);

		public static string Instruction1 => ResourceManager.GetString("Instruction1", resourceCulture);

		public static string InstructionDetail1 => ResourceManager.GetString("InstructionDetail1", resourceCulture);

		public static string Instruction2 => ResourceManager.GetString("Instruction2", resourceCulture);

		public static string InstructionDetail2 => ResourceManager.GetString("InstructionDetail2", resourceCulture);

		public static string Instruction3 => ResourceManager.GetString("Instruction3", resourceCulture);

		public static string InstructionDetail3 => ResourceManager.GetString("InstructionDetail3", resourceCulture);

		public static string SetupButton1 => ResourceManager.GetString("SetupButton1", resourceCulture);

		public static string SetupButton2 => ResourceManager.GetString("SetupButton2", resourceCulture);

		public static string PlayButton1 => ResourceManager.GetString("PlayButton1", resourceCulture);

		public static string PlayButton2 => ResourceManager.GetString("PlayButton2", resourceCulture);

		public static string AchievementLockOption => ResourceManager.GetString("AchievementLockOption", resourceCulture);

		public static string AchievementUnlockOption => ResourceManager.GetString("AchievementUnlockOption", resourceCulture);

		public static string StatsTitle => ResourceManager.GetString("StatsTitle", resourceCulture);

		public static string StatsRarestAchievement => ResourceManager.GetString("StatsRarestAchievement", resourceCulture);

		public static string StatsNoRarestAchievement => ResourceManager.GetString("StatsNoRarestAchievement", resourceCulture);

		public static string StatsRarity => ResourceManager.GetString("StatsRarity", resourceCulture);

		public static string StatsPercentile1 => ResourceManager.GetString("StatsPercentile1", resourceCulture);

		public static string StatsPercentile2 => ResourceManager.GetString("StatsPercentile2", resourceCulture);

		public static string NoScreenshotText => ResourceManager.GetString("NoScreenshotText", resourceCulture);

		public static string SettingsTitle => ResourceManager.GetString("SettingsTitle", resourceCulture);

		public static string SettingsSteamRefreshButton => ResourceManager.GetString("SettingsSteamRefreshButton", resourceCulture);

		public static string SettingsSteamStatus => ResourceManager.GetString("SettingsSteamStatus", resourceCulture);

		public static string SettingsTestNotificationsButton => ResourceManager.GetString("SettingsTestNotificationsButton", resourceCulture);

		public static string SettingsNotificationsDetails => ResourceManager.GetString("SettingsNotificationsDetails", resourceCulture);

		public static string SettingsNotificationsSize => ResourceManager.GetString("SettingsNotificationsSize", resourceCulture);

		public static string SettingsNotificationsTime => ResourceManager.GetString("SettingsNotificationsTime", resourceCulture);

		public static string SettingsNotificationsColor => ResourceManager.GetString("SettingsNotificationsColor", resourceCulture);

		public static string SettingsNotificationsSaveButton1 => ResourceManager.GetString("SettingsNotificationsSaveButton1", resourceCulture);

		public static string SettingsNotificationsSaveButton2 => ResourceManager.GetString("SettingsNotificationsSaveButton2", resourceCulture);

		public static string SettingsLanguageTooltip => ResourceManager.GetString("SettingsLanguageTooltip", resourceCulture);

		public static string ConfirmButton => ResourceManager.GetString("ConfirmButton", resourceCulture);

		public static string CancelButton => ResourceManager.GetString("CancelButton", resourceCulture);

		public static string GameSelectionTitle => ResourceManager.GetString("GameSelectionTitle", resourceCulture);

		public static string GameSelectionButton => ResourceManager.GetString("GameSelectionButton", resourceCulture);
	}
}